import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, ShieldCheck, ChevronRight, Pin, Sparkles, Sliders, Check, ExternalLink } from 'lucide-react';
import { useSettingsStore } from '../stores/useSettingsStore';
import '../index.css';

const Options = () => {
  const [activeSlide, setActiveSlide] = useState(0);
  const [tab, setTab] = useState<'onboarding' | 'settings'>('onboarding');
  const { sensitivityThreshold, setSensitivityThreshold, autoHighlight, setAutoHighlight } =
    useSettingsStore();
  const [saved, setSaved] = useState(false);

  const slides = [
    {
      title: 'Welcome to PRAMAAN',
      subtitle: 'The Real-Time Trust Layer for AI',
      description:
        'PRAMAAN verifies every factual claim generated by ChatGPT, Gemini, Claude, Perplexity, Grok, DeepSeek, and Copilot in real time.',
      icon: Shield,
      badge: 'Step 01 / 03'
    },
    {
      title: 'Pin Extension to Toolbar',
      subtitle: 'Instant Access & Shortcut Control',
      description:
        'Click the puzzle icon in Chrome and pin PRAMAAN. Use Alt + Shift + V anytime on AI websites to toggle the 420px floating workspace.',
      icon: Pin,
      badge: 'Step 02 / 03'
    },
    {
      title: 'Start Verifying Live',
      subtitle: 'Truth. Verified. Always.',
      description:
        'As AI streams answers, complete sentences receive animated green (Verified), yellow (Context), or red (Contradicted) underlines.',
      icon: ShieldCheck,
      badge: 'Step 03 / 03'
    }
  ];

  const handleNextSlide = () => {
    if (activeSlide < slides.length - 1) {
      setActiveSlide(activeSlide + 1);
    } else {
      setTab('settings');
    }
  };

  const handleSaveSettings = () => {
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  return (
    <div className="min-h-screen bg-[#09090B] text-white font-sans p-8 sm:p-12 flex flex-col justify-between selection:bg-purple-600/30">
      {/* Header */}
      <header className="max-w-5xl mx-auto w-full flex items-center justify-between border-b border-white/[0.08] pb-6">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-purple-950/80 border border-purple-500/40 flex items-center justify-center text-purple-300">
            <Shield className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-base font-semibold tracking-wider font-mono uppercase flex items-center gap-2">
              PRAMAAN CONTROL CENTER
              <span className="w-2 h-2 rounded-full bg-purple-500 animate-pulse" />
            </h1>
            <p className="text-xs font-mono text-zinc-500">
              Chrome Extension Settings & Onboarding
            </p>
          </div>
        </div>

        <nav className="flex items-center gap-2 bg-[#111113] p-1 rounded-full border border-white/10 text-xs font-mono">
          <button
            onClick={() => setTab('onboarding')}
            className={`px-4 py-1.5 rounded-full transition-all cursor-pointer ${
              tab === 'onboarding' ? 'bg-purple-600 text-white' : 'text-zinc-400 hover:text-white'
            }`}
          >
            Onboarding Slides
          </button>
          <button
            onClick={() => setTab('settings')}
            className={`px-4 py-1.5 rounded-full transition-all cursor-pointer ${
              tab === 'settings' ? 'bg-purple-600 text-white' : 'text-zinc-400 hover:text-white'
            }`}
          >
            Settings
          </button>
        </nav>
      </header>

      {/* Main Content Body */}
      <main className="max-w-4xl mx-auto w-full my-auto py-12">
        {tab === 'onboarding' && (
          <div className="p-10 sm:p-14 rounded-3xl bg-[#111113] border border-white/10 shadow-2xl space-y-10 text-center relative overflow-hidden">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeSlide}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.4 }}
                className="space-y-6 max-w-xl mx-auto"
              >
                <span className="text-xs font-mono uppercase tracking-widest text-purple-400 px-3 py-1 rounded-full bg-purple-950/40 border border-purple-500/30">
                  {slides[activeSlide].badge}
                </span>

                <div className="w-16 h-16 mx-auto rounded-2xl bg-purple-950/60 border border-purple-500/40 flex items-center justify-center text-purple-300 shadow-[0_0_30px_rgba(124,58,237,0.3)]">
                  {React.createElement(slides[activeSlide].icon, { className: 'w-8 h-8' })}
                </div>

                <h2 className="text-4xl sm:text-5xl font-serif-editorial text-white">
                  {slides[activeSlide].title}
                </h2>

                <p className="text-xs font-mono text-purple-300 uppercase tracking-widest">
                  {slides[activeSlide].subtitle}
                </p>

                <p className="text-zinc-300 text-sm leading-relaxed">
                  {slides[activeSlide].description}
                </p>
              </motion.div>
            </AnimatePresence>

            {/* Slide Navigation Controls */}
            <div className="flex items-center justify-between border-t border-white/[0.08] pt-6">
              <div className="flex items-center gap-2">
                {slides.map((_, idx) => (
                  <button
                    key={idx}
                    onClick={() => setActiveSlide(idx)}
                    className={`w-3 h-3 rounded-full transition-all cursor-pointer ${
                      activeSlide === idx ? 'bg-purple-500 w-8' : 'bg-zinc-800 hover:bg-zinc-700'
                    }`}
                  />
                ))}
              </div>

              <button
                onClick={handleNextSlide}
                className="px-6 py-2.5 rounded-full bg-purple-600 hover:bg-purple-500 text-white font-mono text-xs font-medium uppercase tracking-wider transition-all shadow-[0_0_20px_rgba(124,58,237,0.4)] flex items-center gap-2 cursor-pointer"
              >
                {activeSlide < slides.length - 1 ? 'Next Slide' : 'Launch Settings'}
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        )}

        {tab === 'settings' && (
          <div className="p-10 rounded-3xl bg-[#111113] border border-white/10 shadow-2xl space-y-8">
            <div className="border-b border-white/[0.08] pb-4">
              <h2 className="text-3xl font-serif-editorial text-white">
                Extension Configuration
              </h2>
              <p className="text-xs font-mono text-zinc-400 mt-1">
                Customize verification strictness and DOM auto-highlighting heuristics.
              </p>
            </div>

            <div className="space-y-6">
              {/* Sensitivity threshold */}
              <div className="p-6 rounded-2xl bg-[#09090B] border border-white/[0.06] space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-semibold text-white">
                      Verification Strictness Threshold
                    </h3>
                    <p className="text-xs text-zinc-400">
                      Required confidence percentage before flagging claims as Verified.
                    </p>
                  </div>
                  <span className="text-2xl font-serif-editorial font-bold text-purple-300 font-mono">
                    {sensitivityThreshold}%
                  </span>
                </div>

                <input
                  type="range"
                  min="60"
                  max="99"
                  value={sensitivityThreshold}
                  onChange={(e) => setSensitivityThreshold(Number(e.target.value))}
                  className="w-full accent-purple-500 bg-zinc-800 rounded-lg cursor-pointer"
                />
              </div>

              {/* Auto Highlight Toggle */}
              <div className="p-6 rounded-2xl bg-[#09090B] border border-white/[0.06] flex items-center justify-between">
                <div>
                  <h3 className="text-sm font-semibold text-white">
                    Auto-Inject Sentence Underlines
                  </h3>
                  <p className="text-xs text-zinc-400">
                    Automatically underline verified sentences inside target LLM host pages.
                  </p>
                </div>
                <button
                  onClick={() => setAutoHighlight(!autoHighlight)}
                  className={`w-12 h-6 rounded-full transition-colors relative p-1 cursor-pointer ${
                    autoHighlight ? 'bg-purple-600' : 'bg-zinc-800'
                  }`}
                >
                  <div
                    className={`w-4 h-4 rounded-full bg-white transition-transform ${
                      autoHighlight ? 'translate-x-6' : 'translate-x-0'
                    }`}
                  />
                </button>
              </div>

              {/* Save action */}
              <div className="pt-4 flex justify-end">
                <button
                  onClick={handleSaveSettings}
                  className="px-7 py-3 rounded-full bg-purple-600 hover:bg-purple-500 text-white font-mono text-xs font-semibold uppercase tracking-wider transition-all shadow-[0_0_20px_rgba(124,58,237,0.4)] flex items-center gap-2 cursor-pointer"
                >
                  {saved ? (
                    <>
                      <Check className="w-4 h-4 text-emerald-300" /> Settings Saved
                    </>
                  ) : (
                    'Save Preferences'
                  )}
                </button>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="max-w-5xl mx-auto w-full border-t border-white/[0.08] pt-6 flex items-center justify-between text-xs font-mono text-zinc-500">
        <span>PRAMAAN Chrome Extension Engine v2.4.0</span>
        <span>Manifest V3 Production Build</span>
      </footer>
    </div>
  );
};

const root = createRoot(document.getElementById('root') || document.body);
root.render(<Options />);
