import React from 'react';
import { motion } from 'framer-motion';
import { ShieldCheck, Play } from 'lucide-react';
import { MagneticButton } from '../common/MagneticButton';

interface HeroSectionProps {
  onStartDemo: () => void;
  onOpenWorkspace: () => void;
}

export const HeroSection: React.FC<HeroSectionProps> = ({
  onStartDemo,
  onOpenWorkspace,
}) => {
  return (
    <section className="relative min-h-[92vh] pt-36 pb-20 px-6 flex flex-col justify-center items-center text-center overflow-hidden radial-beam-hero">
      {/* Top trust pill */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-[#111113] border border-white/10 text-xs font-mono text-zinc-300 mb-10 shadow-xl"
      >
        <span className="flex h-2 w-2 relative">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-purple-400 opacity-75"></span>
          <span className="relative inline-flex rounded-full h-2 w-2 bg-purple-500"></span>
        </span>
        <span className="text-zinc-400">PRAMAAN Engine v2.4</span>
        <span className="text-zinc-600">•</span>
        <span className="text-purple-300">Live Verification Active</span>
      </motion.div>

      {/* Massive Editorial Headline */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.9, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
        className="max-w-5xl mx-auto space-y-2"
      >
        <h1 className="text-7xl sm:text-8xl md:text-9xl font-serif-editorial tracking-tight text-white leading-[0.9] select-none">
          Truth. <br />
          <span className="italic font-normal bg-gradient-to-r from-white via-purple-200 to-purple-400 bg-clip-text text-transparent">
            Verified.
          </span>{' '}
          Always.
        </h1>
      </motion.div>

      {/* Subtitle */}
      <motion.p
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.9, delay: 0.25, ease: [0.16, 1, 0.3, 1] }}
        className="max-w-2xl mx-auto mt-8 text-lg sm:text-xl text-zinc-400 leading-relaxed font-normal"
      >
        PRAMAAN is the trust layer for AI. We verify every factual claim generated by large language models in real time using evidence from peer-reviewed databases and primary sources.
      </motion.p>

      {/* Action Buttons */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.9, delay: 0.35, ease: [0.16, 1, 0.3, 1] }}
        className="mt-12 flex flex-wrap items-center justify-center gap-5"
      >
        <MagneticButton onClick={onOpenWorkspace} variant="primary">
          <ShieldCheck className="w-4 h-4 text-black" />
          Add to Chrome — Free
        </MagneticButton>

        <MagneticButton onClick={onStartDemo} variant="secondary">
          <Play className="w-3.5 h-3.5 fill-current text-purple-400" />
          Watch Live Demo
        </MagneticButton>
      </motion.div>

      {/* Supported LLM bar */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1, delay: 0.5 }}
        className="mt-20 pt-8 border-t border-white/[0.06] max-w-4xl mx-auto w-full flex flex-col items-center gap-4"
      >
        <span className="text-xs font-mono uppercase tracking-widest text-zinc-500">
          Native Real-Time Protection Layer For
        </span>
        <div className="flex flex-wrap items-center justify-center gap-8 text-sm font-medium text-zinc-400">
          <span className="hover:text-white transition-colors cursor-default">ChatGPT</span>
          <span className="text-zinc-700">•</span>
          <span className="hover:text-white transition-colors cursor-default">Gemini</span>
          <span className="text-zinc-700">•</span>
          <span className="hover:text-white transition-colors cursor-default">Claude</span>
          <span className="text-zinc-700">•</span>
          <span className="hover:text-white transition-colors cursor-default">Perplexity</span>
          <span className="text-zinc-700">•</span>
          <span className="hover:text-white transition-colors cursor-default">Grok</span>
          <span className="text-zinc-700">•</span>
          <span className="hover:text-white transition-colors cursor-default">DeepSeek</span>
        </div>
      </motion.div>
    </section>
  );
};
