import React, { useState } from "react";
import { Modal } from "../../components/ui/Modal";
import { Button } from "../../components/ui/Button";
import { ShieldCheck, Pin, Cpu, Layers, CheckCircle2, ChevronRight, Check } from "lucide-react";
import { useUIStore } from "../../stores/ui.store";

export const OnboardingModal: React.FC = () => {
  const { isOnboardingCompleted, setOnboardingCompleted } = useUIStore();
  const [step, setStep] = useState(0);

  if (isOnboardingCompleted) return null;

  const steps = [
    {
      title: "Welcome to PRAMAAN",
      subtitle: "AI Trust Layer",
      icon: <ShieldCheck className="w-10 h-10 text-accent" />,
      content:
        "PRAMAAN verifies every factual claim generated by AI models in real time as responses stream. Built for accuracy, transparency, and speed."
    },
    {
      title: "Pin Extension to Toolbar",
      subtitle: "Instant browser access",
      icon: <Pin className="w-10 h-10 text-status-warning" />,
      content:
        "Click the extension puzzle icon in your browser toolbar and pin PRAMAAN for one-click access to history, settings, and live verification status."
    },
    {
      title: "Supported AI Platforms",
      subtitle: "Seamless native integration",
      icon: <Cpu className="w-10 h-10 text-accent" />,
      content:
        "Works across ChatGPT, Gemini, Claude, Perplexity, Grok, DeepSeek, and Copilot without breaking website layouts or performance."
    },
    {
      title: "How Verification Works",
      subtitle: "Incremental streaming analysis",
      icon: <Layers className="w-10 h-10 text-status-success" />,
      content:
        "Sentences are extracted as text streams, cross-referenced against peer-reviewed academic indexes, and highlighted with credibility ratings."
    },
    {
      title: "You're All Set!",
      subtitle: "Ready for live fact verification",
      icon: <CheckCircle2 className="w-10 h-10 text-status-success" />,
      content:
        "Start chatting with any supported AI platform. Use Alt + Shift + V at any time to toggle your floating PRAMAAN sidebar."
    }
  ];

  const current = steps[step];

  const handleNext = () => {
    if (step < steps.length - 1) {
      setStep(step + 1);
    } else {
      setOnboardingCompleted(true);
    }
  };

  return (
    <Modal isOpen={!isOnboardingCompleted} onClose={() => setOnboardingCompleted(true)}>
      <div className="text-center space-y-4 py-2 select-none">
        <div className="w-16 h-16 rounded-32 bg-surface-elevated border border-border flex items-center justify-center mx-auto shadow-glass">
          {current.icon}
        </div>

        <div>
          <h2 className="text-lg font-bold text-primary">{current.title}</h2>
          <p className="text-xs font-mono text-accent uppercase tracking-wider mt-0.5">
            {current.subtitle}
          </p>
        </div>

        <p className="text-xs text-primary-muted leading-relaxed max-w-sm mx-auto">
          {current.content}
        </p>

        {/* Step Progress Dots */}
        <div className="flex items-center justify-center gap-1.5 pt-2">
          {steps.map((_, idx) => (
            <span
              key={idx}
              className={`h-1.5 rounded-full transition-all duration-300 ${
                idx === step ? "w-6 bg-accent" : "w-1.5 bg-white/20"
              }`}
            />
          ))}
        </div>

        <div className="flex items-center justify-between pt-4 border-t border-border">
          <Button
            size="sm"
            variant="ghost"
            onClick={() => setOnboardingCompleted(true)}
          >
            Skip Intro
          </Button>
          <Button
            size="sm"
            variant="primary"
            rightIcon={step === steps.length - 1 ? <Check className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
            onClick={handleNext}
          >
            {step === steps.length - 1 ? "Get Started" : "Continue"}
          </Button>
        </div>
      </div>
    </Modal>
  );
};
